media: images
content:
  - name: data
    label: 全部数据（JSON）
    type: file
    path: data.json
    fields:
      - name: body
        label: 网站数据
        type: code
        options:
          language: json
