backend:
  name: github
  repo: zha-rujing-lab/zha-rujing-lab.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "网站内容"
    files:
      - name: "data"
        label: "全部数据（JSON）"
        file: "data.json"
        fields:
          - { label: "数据", name: "data", widget: "code", default_language: "json" }
